### ISSUE TITLE
*This station's rating is not up to date

### ISSUE THREAD

**Issue by oeon** [SLUGIS/smokeybear#3]
seems to always say `*This station's rating is not up to date` for Arroyo Grande

**Comment by kaysabelle** [comment]
For some reason I'm not receiving any data for Arroyo Grande that has `<nfdr_type>O</nfdr_type>` with `<msgc>7G3A2</msgc>`. I am receiving data with those 2 criteria for the other two stations though. I will investigate this more tomorrow.

**Comment by oeon** [comment]
`7G3A2` not available here: https://fam.nwcg.gov/wims/xsql/nfdrs.xsql?stn=44915&sig=&type=&start=22-APR-15&end=22-APR-15&time=&user=4e1&priority= but `7G2A2` is :-/ prolly my bad on initial direction there. Fixed ae072cb882f91d7e214193afcf6fedf7f2aa1a38
